create table vsr_citizenships
(
    code        int primary key,
    description text not null
);

create temp table temp_citizenships
(
    code        text,
    description text
);

copy temp_citizenships from '/var/lib/postgresql/vsr_data/VSR-Citizenship.csv' with (format csv, header);

insert into vsr_citizenships as vc
select nullif(regexp_replace(code, '[^0-9]', '', 'g'), '')::int, trim(description)
from temp_citizenships as tc
where code is not null
  and trim(code) != ''
on conflict do nothing;

create table vsr_icd10_codes
(
    code        varchar(8) primary key,
    description text not null
);

create temp table temp_icd10
(
    code        text,
    description text
);

copy temp_icd10 from '/var/lib/postgresql/vsr_data/VSR-ICD10.csv' with (format csv, header);

insert into vsr_icd10_codes
select trim(regexp_replace(code, '[^a-zA-Z0-9.]', '', 'g')), trim(description)
from temp_icd10
where code is not null
  and trim(code) != ''
on conflict (code) do nothing;

create table vsr_tablist
(
    code        varchar(16) primary key,
    description text not null
);

create temp table temp_tablist
(
    code        text,
    description text,
    icd10_codes text
);

copy temp_tablist from '/var/lib/postgresql/vsr_data/VSR-Tablist.csv' with (format csv, header);

insert into vsr_tablist
select trim(regexp_replace(code, '[^a-zA-Z0-9.-]', '', 'g')), trim(description)
from temp_tablist
where code is not null
  and trim(code) != ''
on conflict (code) do nothing;

create table vsr_sex
(
    code        int generated by default as identity primary key,
    description text not null,

    constraint uq_vsr_sex_description unique (description)
);

insert into vsr_sex (code, description)
values (1, 'Male')
     , (2, 'Female');

create table vsr_civil_statuses
(
    code        int generated by default as identity primary key,
    description text not null,

    constraint uq_vsr_civil_status_description unique (description)
);

insert into vsr_civil_statuses (code, description)
values (1, 'Single')
     , (2, 'Married')
     , (3, 'Widower')
     , (4, 'Divorced')
     , (9, 'Not Stated');

create table vsr_place_types
(
    code        int generated by default as identity primary key,
    description text not null,

    constraint uq_vsr_site_of_occurence_description unique (description)
);

insert into vsr_place_types
values (1, 'Hospital')
     , (2, 'Home')
     , (3, 'Others')
     , (9, 'Not Stated');

create table vsr_attendants
(
    code        int generated by default as identity primary key,
    description text not null,

    constraint uq_vsr_attendant_at_death_description unique (description)
);

insert into vsr_attendants
values (1, 'Private Physician')
     , (2, 'Public Health Officer')
     , (3, 'Hospital Authority')
     , (4, 'None')
     , (5, 'Others')
     , (9, 'Not Stated');

create table vsr_registration_statuses
(
    code        int generated by default as identity primary key,
    description text not null,

    constraint uq_vsr_registration_status_description unique (description)
);

insert into vsr_registration_statuses
values (1, 'Timely')
     , (2, 'Late');

create temp table temp_death_raw_data
(
    month_of_death              int,
    day_of_death                int,
    year_of_death               int,
    place_of_death_region       int,
    place_of_death_province     int,
    place_of_death_mun          int,
    place_of_death_region_new   int,
    place_of_death_province_new int,
    place_of_death_mun_new      int,
    sex                         int,
    age                         int,
    residence_region            int,
    residence_province          int,
    residence_mun               int,
    residence_region_new        int,
    residence_province_new      int,
    residence_mun_new           int,
    civil_status                int,
    citizenship                 int,
    place_type                  int,
    attendant                   int,
    registration_status         int,
    icd_code_3d                 varchar(8),
    tablist                     varchar(16)
);

copy temp_death_raw_data from '/var/lib/postgresql/vsr_data/VSR-Death-Data.csv' with (format csv, header);

analyze temp_death_raw_data;

create index idx_temp_pod on temp_death_raw_data (place_of_death_region_new, place_of_death_province_new,
                                                  place_of_death_mun_new);

create index idx_temp_res on temp_death_raw_data (residence_region_new, residence_province_new, residence_mun_new);

create table vsr_deaths
(
    id                        int generated always as identity primary key,
    month_of_death            int        not null,
    day_of_death              int        not null,
    year_of_death             int        not null,
    municipality_of_death_id  int,
    sex                       int        not null,
    age                       int        not null,
    age_years                 int,
    infant_age_days           int,
    residence_municipality_id int,
    civil_status              int,
    citizenship               int,
    place_type                int,
    attendant                 int        not null,
    registration_status       int        not null,
    icd10_code                varchar(8) not null,
    tablist                   varchar(16)
);

with psgc_table as ( select pr.code reg_code, pp.code as prov_code, pm.code as mun_code, pm.id as mun_id
                     from psgc_municipalities pm
                              join psgc_provinces pp on pm.province_id = pp.id
                              join psgc_regions pr on pp.region_code = pr.code )
insert
into vsr_deaths ( month_of_death, day_of_death, year_of_death, municipality_of_death_id, sex, age, age_years
                , infant_age_days, residence_municipality_id, civil_status, citizenship, place_type, attendant
                , registration_status
                , icd10_code, tablist)
select month_of_death
     , day_of_death
     , year_of_death
     , pod.mun_id
     , sex
     , age
     , case when tdrd.age between 201 and 299 then tdrd.age - 200
            when tdrd.age >= 300 and tdrd.age < 999 then tdrd.age - 300
            when tdrd.age between 0 and 111 then 0 end
     , case when tdrd.age between 0 and 30 then tdrd.age
            when tdrd.age between 101 and 111 then (tdrd.age - 100) * 30 end
     , res.mun_id
     , civil_status
     , citizenship
     , place_type
     , attendant
     , registration_status
     , icd_code_3d
     , tablist
from temp_death_raw_data as tdrd
         left join psgc_table pod
              on tdrd.place_of_death_region_new = pod.reg_code and tdrd.place_of_death_province_new = pod.prov_code and
                 tdrd.place_of_death_mun_new = pod.mun_code
         left join psgc_table res
              on tdrd.residence_region_new = res.reg_code and tdrd.residence_province_new = res.prov_code and
                 tdrd.residence_mun_new = res.mun_code;

alter table vsr_deaths
    add constraint fk_vsr_deaths_municipality_of_death_id foreign key (municipality_of_death_id) references psgc_municipalities (id),
    add constraint fk_vsr_deaths_residence_municipality_id foreign key (residence_municipality_id) references psgc_municipalities (id),
    add constraint fk_vsr_deaths_civil_status foreign key (civil_status) references vsr_civil_statuses (code),
    add constraint fk_vsr_deaths_citizenship foreign key (citizenship) references vsr_citizenships (code),
    add constraint fk_vsr_deaths_place_type foreign key (place_type) references vsr_place_types (code),
    add constraint fk_vsr_deaths_attendant foreign key (attendant) references vsr_attendants (code),
    add constraint fk_vsr_deaths_registration_status foreign key (registration_status) references vsr_registration_statuses (code),
    add constraint fk_vsr_deaths_icd10_code foreign key (icd10_code) references vsr_icd10_codes (code),
    add constraint fk_vsr_deaths_tablist foreign key (tablist) references vsr_tablist (code),
    add constraint fk_vsr_deaths_sex foreign key (sex) references vsr_sex (code);

create index idx_vsr_deaths_date_of_death on vsr_deaths (year_of_death, month_of_death, day_of_death);
create index idx_vsr_deaths_sex on vsr_deaths (sex);
create index idx_vsr_deaths_icd10_code on vsr_deaths (icd10_code);
