create table vsr_birth_attendants
(
    code        int generated by default as identity primary key,
    description text,

    constraint uq_vsr_birth_attendants_description unique (description)
);

insert into vsr_birth_attendants as vba (code, description)
values (1, 'Physician')
     , (2, 'Nurse')
     , (3, 'Midwife')
     , (4, 'Traditional Birth Attendant')
     , (5, 'Others')
     , (9, 'Not Stated');

create table vsr_birth_place_types
(
    code        int generated by default as identity primary key,
    description text,

    constraint uq_vsr_birth_place_types_description unique (description)
);

insert into vsr_birth_place_types as vbpt (code, description)
values (1, 'Health Facility')
     , (2, 'Home')
     , (3, 'Others')
     , (9, 'Not Stated');

create table vsr_birth_legitimacy_statuses
(
    code        int generated by default as identity primary key,
    description text,

    constraint uq_vsr_birth_legitimacy_statuses_description unique (description)
);

insert into vsr_birth_legitimacy_statuses as vbls (code, description)
values (1, 'Marital')
     , (2, 'Non-marital');

create temp table temp_vsr_births_ingest
(
    birth_place_region            int,
    birth_place_province          int,
    birth_place_mun               int,
    new_birth_place_region        int,
    new_birth_place_province      int,
    new_birth_place_mun           int,
    mother_residence_region       int,
    mother_residence_province     int,
    mother_residence_mun          int,
    new_mother_residence_region   int,
    new_mother_residence_province int,
    new_mother_residence_mun      int,
    sex                           int,
    date_birth_day                int,
    date_birth_month              int,
    date_birth_year               int,
    place_type                    int,
    attendant                     int,
    birth_order                   int,
    birth_weight                  int,
    children_still_living         int,
    mother_age                    int,
    father_age                    int,
    mother_citizenship            int,
    father_citizenship            int,
    legitimacy_status             int,
    registration_status           int
);

copy temp_vsr_births_ingest from '/var/lib/postgresql/vsr_data/VSR-Births-Male.csv' (format csv, header);
copy temp_vsr_births_ingest from '/var/lib/postgresql/vsr_data/VSR-Births-Female.csv' (format csv, header);

analyze temp_vsr_births_ingest;

create index idx_temp_vsr_births_ingest_birth_place on temp_vsr_births_ingest (new_birth_place_region, new_birth_place_province, new_birth_place_mun);
create index idx_temp_vsr_births_ingest_mothers_residence on temp_vsr_births_ingest (new_mother_residence_region,
                                                                                     new_mother_residence_province,
                                                                                     new_mother_residence_mun);

create table vsr_births
(
    id                      int generated always as identity primary key,
    birth_place_mun_id      int not null,
    mother_residence_mun_id int not null,
    sex                     int not null,
    date_birth_day          int not null,
    date_birth_month        int not null,
    date_birth_year         int not null,
    place_type              int not null,
    attendant               int not null,
    birth_order             int not null,
    birth_weight            int not null,
    children_still_living   int not null,
    mother_age              int not null,
    father_age              int not null,
    mother_citizenship      int not null,
    father_citizenship      int not null,
    legitimacy_status       int not null,
    registration_status     int not null
);

with psgc_table as ( select pr.code as reg_code, pp.code as prov_code, pm.code as mun_code, pm.id as mun_id
                     from psgc_municipalities pm
                              join psgc_provinces pp on pm.province_id = pp.id
                              join psgc_regions pr on pp.region_code = pr.code )
insert
into vsr_births as vb ( birth_place_mun_id, mother_residence_mun_id, sex, date_birth_day, date_birth_month
                      , date_birth_year, place_type, attendant, birth_order, birth_weight, children_still_living
                      , mother_age, father_age, mother_citizenship, father_citizenship, legitimacy_status
                      , registration_status)
select ptb.mun_id
     , ptm.mun_id
     , sex
     , date_birth_day
     , date_birth_month
     , date_birth_year
     , place_type
     , attendant
     , birth_order
     , birth_weight
     , children_still_living
     , mother_age
     , father_age
     , mother_citizenship
     , father_citizenship
     , legitimacy_status
     , registration_status
from temp_vsr_births_ingest as tvbi
         join psgc_table ptb
              on tvbi.new_birth_place_region = ptb.reg_code and tvbi.new_birth_place_province = ptb.prov_code and
                 tvbi.new_birth_place_mun = ptb.mun_code
         join psgc_table ptm on tvbi.new_mother_residence_region = ptm.reg_code and
                                tvbi.new_mother_residence_province = ptm.prov_code and
                                tvbi.new_mother_residence_mun = ptm.mun_code;

alter table vsr_births
    add constraint fk_vsr_births_sex foreign key (sex) references vsr_sex (code),
    add constraint fk_vsr_births_place_type foreign key (place_type) references vsr_birth_place_types (code),
    add constraint fk_vsr_births_attendant foreign key (attendant) references vsr_birth_attendants (code),
    add constraint fk_vsr_births_mother_citizenship foreign key (mother_citizenship) references vsr_citizenships (code),
    add constraint fk_vsr_births_father_citizenship foreign key (father_citizenship) references vsr_citizenships (code),
    add constraint fk_vsr_births_legitimacy_status foreign key (legitimacy_status) references vsr_birth_legitimacy_statuses (code),
    add constraint fk_vsr_births_registration_status foreign key (registration_status) references vsr_registration_statuses (code);
