set local work_mem = '512MB';

create table vsr_citizenships
(
    code        int primary key,
    description text not null
);

create temp table temp_citizenships
(
    code        text,
    description text
);

copy temp_citizenships from '/var/lib/postgresql/vsr_data/VSR-Citizenship.csv' with (format csv, header);

insert into vsr_citizenships as vc
select nullif(regexp_replace(code, '[^0-9]', '', 'g'), '')::int, trim(description)
from temp_citizenships as tc
where code is not null
  and trim(code) != ''
on conflict do nothing;

create table vsr_icd10_codes
(
    code        varchar(8) primary key,
    description text not null
);

create temp table temp_icd10
(
    code        text,
    description text
);

copy temp_icd10 from '/var/lib/postgresql/vsr_data/VSR-ICD10.csv' with (format csv, header);

insert into vsr_icd10_codes
select trim(regexp_replace(code, '[^a-zA-Z0-9.]', '', 'g')), trim(description)
from temp_icd10
where code is not null
  and trim(code) != ''
on conflict (code) do nothing;

insert into vsr_icd10_codes (code, description)
values ('U07', 'Emergency use of U07 (COVID-19 and Vaping-related disorders)')
     , ('U10', 'Multisystem inflammatory syndrome associated with COVID-19')
     , ('U049', 'Severe acute respiratory syndrome [SARS], unspecified')
     , ('I84', 'Haemorrhoids')
on conflict (code) do nothing;

create table vsr_tablist
(
    code        varchar(16) primary key,
    description text not null
);

create temp table temp_tablist
(
    code        text,
    description text,
    icd10_codes text
);

copy temp_tablist from '/var/lib/postgresql/vsr_data/VSR-Tablist.csv' with (format csv, header);

insert into vsr_tablist
select trim(regexp_replace(code, '[^a-zA-Z0-9.-]', '', 'g')), trim(description)
from temp_tablist
where code is not null
  and trim(code) != ''
on conflict (code) do nothing;

create table vsr_sex
(
    code        int generated by default as identity primary key,
    description text not null,

    constraint uq_vsr_sex_description unique (description)
);

insert into vsr_sex (code, description)
values (1, 'Male')
     , (2, 'Female');

create table vsr_civil_statuses
(
    code        int generated by default as identity primary key,
    description text not null,

    constraint uq_vsr_civil_status_description unique (description)
);

insert into vsr_civil_statuses (code, description)
values (1, 'Single')
     , (2, 'Married')
     , (3, 'Widower')
     , (4, 'Divorced')
     , (9, 'Not Stated');

create table vsr_place_types
(
    code        int generated by default as identity primary key,
    description text not null,

    constraint uq_vsr_site_of_occurence_description unique (description)
);

insert into vsr_place_types
values (1, 'Hospital')
     , (2, 'Home')
     , (3, 'Others')
     , (9, 'Not Stated');

create table vsr_attendants
(
    code        int generated by default as identity primary key,
    description text not null,

    constraint uq_vsr_attendant_at_death_description unique (description)
);

insert into vsr_attendants
values (1, 'Private Physician')
     , (2, 'Public Health Officer')
     , (3, 'Hospital Authority')
     , (4, 'None')
     , (5, 'Others')
     , (9, 'Not Stated');

create table vsr_registration_statuses
(
    code        int generated by default as identity primary key,
    description text not null,

    constraint uq_vsr_registration_status_description unique (description)
);

insert into vsr_registration_statuses
values (1, 'Timely')
     , (2, 'Late');

create table staging.vsr_deaths_2023_2024
(
    date_of_death_month         int,
    date_of_death_day           int,
    date_of_death_year          int,
    place_of_death_region       varchar(2),
    place_of_death_province     varchar(3),
    place_of_death_mun          varchar(2),
    place_of_death_region_new   varchar(2),
    place_of_death_province_new varchar(3),
    place_of_death_mun_new      varchar(2),
    sex                         int,
    age                         int,
    residence_region            varchar(2),
    residence_province          varchar(3),
    residence_mun               varchar(2),
    residence_region_new        varchar(2),
    residence_province_new      varchar(3),
    residence_mun_new           varchar(2),
    civil_status                int,
    citizenship                 int,
    place_type                  int,
    attendant                   int,
    registration_status         int,
    icd_code                    varchar(8),
    tablist                     varchar(16)
);

copy staging.vsr_deaths_2023_2024 from '/var/lib/postgresql/vsr_data/VSR-PUF-2024-Death.csv' with (format csv, header);
copy staging.vsr_deaths_2023_2024 from '/var/lib/postgresql/vsr_data/VSR-PUF-2023-Death.csv' with (format csv, header);

create table staging.temp_vsr_deaths_2021_2022
(
    date_of_death_month     int,
    date_of_death_day       int,
    date_of_death_year      int,
    place_of_death_region   varchar(2),
    place_of_death_province varchar(3),
    place_of_death_mun      varchar(2),
    sex                     int,
    age                     int,
    residence_region        varchar(2),
    residence_province      varchar(3),
    residence_mun           varchar(2),
    icd_code                varchar(8),
    attendant               int,
    place_type              int,
    registration_status     int
);

copy staging.temp_vsr_deaths_2021_2022 from '/var/lib/postgresql/vsr_data/VSR-PUF-2022-Death.csv' with (format csv, header);
copy staging.temp_vsr_deaths_2021_2022 from '/var/lib/postgresql/vsr_data/VSR-PUF-2021-Death.csv' with (format csv, header);

create table staging.vsr_deaths_2013_2020
(
    date_of_death_month     int,
    date_of_death_day       int,
    date_of_death_year      int,
    place_of_death_region   varchar(2),
    place_of_death_province varchar(3),
    place_of_death_mun      varchar(2),
    sex                     int,
    age                     int,
    residence_region        varchar(2),
    residence_province      varchar(3),
    residence_mun           varchar(2),
    icd_code                varchar(8),
    attendant               int,
    place_type              int,
    registration_status     int
);

copy staging.vsr_deaths_2013_2020 from '/var/lib/postgresql/vsr_data/VSR-PUF-2020-Death.csv' with (format csv, header);
copy staging.vsr_deaths_2013_2020 from '/var/lib/postgresql/vsr_data/VSR-PUF-2019-Death.csv' with (format csv, header);
copy staging.vsr_deaths_2013_2020 from '/var/lib/postgresql/vsr_data/VSR-PUF-2018-Death.csv' with (format csv, header);
copy staging.vsr_deaths_2013_2020 from '/var/lib/postgresql/vsr_data/VSR-PUF-2017-Death.csv' with (format csv, header);
copy staging.vsr_deaths_2013_2020 from '/var/lib/postgresql/vsr_data/VSR-PUF-2016-Death.csv' with (format csv, header);
copy staging.vsr_deaths_2013_2020 from '/var/lib/postgresql/vsr_data/VSR-PUF-2015-Death.csv' with (format csv, header);
copy staging.vsr_deaths_2013_2020 from '/var/lib/postgresql/vsr_data/VSR-PUF-2014-Death.csv' with (format csv, header);
copy staging.vsr_deaths_2013_2020 from '/var/lib/postgresql/vsr_data/VSR-PUF-2013-Death.csv' with (format csv, header);

create table staging.vsr_deaths_pre_2013
(
    date_of_death_month     int,
    date_of_death_day       int,
    date_of_death_year      int,
    place_of_death_region   varchar(2),
    place_of_death_province varchar(3),
    place_of_death_mun      varchar(2),
    sex                     int,
    age                     int,
    residence_region        varchar(2),
    residence_province      varchar(3),
    residence_mun           varchar(2),
    icd_code                varchar(8),
    attendant               int,
    registration_status     int
);

copy staging.vsr_deaths_pre_2013 from '/var/lib/postgresql/vsr_data/VSR-PUF-2012-Death.csv' with (format csv, header);
copy staging.vsr_deaths_pre_2013 from '/var/lib/postgresql/vsr_data/VSR-PUF-2011-Death.csv' with (format csv, header);
copy staging.vsr_deaths_pre_2013 from '/var/lib/postgresql/vsr_data/VSR-PUF-2010-Death.csv' with (format csv, header);
copy staging.vsr_deaths_pre_2013 from '/var/lib/postgresql/vsr_data/VSR-PUF-2009-Death.csv' with (format csv, header);
copy staging.vsr_deaths_pre_2013 from '/var/lib/postgresql/vsr_data/VSR-PUF-2008-Death.csv' with (format csv, header);
copy staging.vsr_deaths_pre_2013 from '/var/lib/postgresql/vsr_data/VSR-PUF-2007-Death.csv' with (format csv, header);
copy staging.vsr_deaths_pre_2013 from '/var/lib/postgresql/vsr_data/VSR-PUF-2006-Death.csv' with (format csv, header);

update staging.vsr_deaths_2023_2024 t
set place_of_death_region       = lpad(place_of_death_region, 2, '0')
  , place_of_death_province  = lpad(place_of_death_province, 3, '0')
  , place_of_death_mun          = lpad(place_of_death_mun, 2, '0')
  , place_of_death_region_new   = lpad(place_of_death_region_new, 2, '0')
  , place_of_death_province_new = lpad(place_of_death_province_new, 3, '0')
  , place_of_death_mun_new      = lpad(place_of_death_mun_new, 2, '0')
  , residence_region            = lpad(residence_region, 2, '0')
  , residence_province = lpad(residence_province, 3, '0')
  , residence_mun               = lpad(residence_mun, 2, '0')
  , residence_region_new        = lpad(residence_region_new, 2, '0')
  , residence_province_new      = lpad(residence_province_new, 3, '0')
  , residence_mun_new           = lpad(residence_mun_new, 2, '0');

update staging.temp_vsr_deaths_2021_2022
set place_of_death_region   = lpad(place_of_death_region, 2, '0')
  , place_of_death_province = lpad(place_of_death_province, 3, '0')
  , place_of_death_mun      = lpad(place_of_death_mun, 2, '0')
  , residence_region        = lpad(residence_region, 2, '0')
  , residence_province      = lpad(residence_province, 3, '0')
  , residence_mun           = lpad(residence_mun, 2, '0');

update staging.vsr_deaths_2013_2020
set place_of_death_region   = lpad(place_of_death_region, 2, '0')
  , residence_region        = lpad(residence_region, 2, '0');

update staging.vsr_deaths_pre_2013
set place_of_death_region   = lpad(place_of_death_region, 2, '0')
  , residence_region        = lpad(residence_region, 2, '0');

update staging.vsr_deaths_2023_2024
set place_of_death_mun_new = '00' where place_of_death_mun_new is null;

update staging.vsr_deaths_2023_2024
set residence_mun_new = '00' where residence_mun_new is null;

update staging.temp_vsr_deaths_2021_2022
set place_of_death_mun = '00' where place_of_death_mun is null;

update staging.temp_vsr_deaths_2021_2022
set residence_mun = '00' where residence_mun is null;

update staging.vsr_deaths_2013_2020
set place_of_death_mun = '00' where place_of_death_mun is null;

update staging.vsr_deaths_2013_2020 v
set residence_mun = '00' where residence_mun is null;

update staging.vsr_deaths_pre_2013
set place_of_death_mun = '00' where place_of_death_mun is null;

update staging.vsr_deaths_pre_2013
set residence_mun = '00' where residence_mun is null;

analyze staging.vsr_deaths_2023_2024;
analyze staging.temp_vsr_deaths_2021_2022;
analyze staging.vsr_deaths_2013_2020;
analyze staging.vsr_deaths_pre_2013;

create index idx_staging_temp_vd_2324_a on staging.vsr_deaths_2023_2024 (date_of_death_year);

create index idx_staging_temp_vd_2324_n on staging.vsr_deaths_2023_2024 (place_of_death_region_new,
                                                                      place_of_death_province_new,
                                                                      place_of_death_mun_new);

create index idx_staging_temp_vd_2324 on staging.vsr_deaths_2023_2024 (place_of_death_region, place_of_death_province, place_of_death_mun);
create index idx_staging_temp_vd_2122 on staging.temp_vsr_deaths_2021_2022 (place_of_death_region, place_of_death_province, place_of_death_mun);
create index idx_staging_temp_vd_1320_p on staging.vsr_deaths_2013_2020 (place_of_death_region, place_of_death_province, place_of_death_mun);
create index idx_staging_temp_vd_2324_p on staging.vsr_deaths_pre_2013 (place_of_death_region, place_of_death_province, place_of_death_mun);

create index idx_staging_temp_vd_2324_r on staging.vsr_deaths_2023_2024 (residence_region, residence_province, residence_mun);
create index idx_staging_temp_vd_2122_r on staging.temp_vsr_deaths_2021_2022 (residence_region, residence_province, residence_mun);
create index idx_staging_temp_vd_1320_r on staging.vsr_deaths_2013_2020 (residence_region, residence_province, residence_mun);
create index idx_staging_temp_vd_pre_2013_r on staging.vsr_deaths_pre_2013 (residence_region, residence_province, residence_mun);

create table staging.vsr_deaths
(
    date_of_death_month         int,
    date_of_death_day           int,
    date_of_death_year          int,
    place_of_death_region       varchar(2),
    place_of_death_province     varchar(3),
    place_of_death_mun          varchar(2),
    place_of_death_region_new   varchar(2),
    place_of_death_province_new varchar(3),
    place_of_death_mun_new      varchar(2),
    place_of_death_psgc_rev_1   char(10),
    sex                         int,
    age                         int,
    age_years                   int,
    infant_age_days             int,
    residence_region            varchar(2),
    residence_province          varchar(3),
    residence_mun               varchar(2),
    residence_region_new        varchar(2),
    residence_province_new      varchar(3),
    residence_mun_new           varchar(2),
    residence_psgc_rev_1        char(10),
    civil_status                int,
    citizenship                 int,
    place_type                  int,
    attendant                   int,
    registration_status         int,
    icd_code                    varchar(8),
    tablist                     varchar(16)
);
